// <auto-generated />
using System;
using DBController;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBController.Migrations
{
    [DbContext(typeof(DBControllerCtx))]
    [Migration("20241004234944_1_Creation_Users_Teams_Tables_05_10_2024_Issue_2")]
    partial class _1_Creation_Users_Teams_Tables_05_10_2024_Issue_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBController.Models.Teams", b =>
                {
                    b.Property<int>("Team_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Team_Id"));

                    b.Property<string>("Team_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Team_Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Team_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Team_Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DBController.Models.Users", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<string>("User_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_TeamId")
                        .HasColumnType("int");

                    b.HasKey("User_Id");

                    b.HasIndex("User_TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DBController.Models.Users", b =>
                {
                    b.HasOne("DBController.Models.Teams", "User_Team")
                        .WithMany()
                        .HasForeignKey("User_TeamId");

                    b.Navigation("User_Team");
                });
#pragma warning restore 612, 618
        }
    }
}
